name: 'Build'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.0.0
    - run: dotnet restore
    - run: dotnet build --no-restore
    - uses: zcong1993/setup-timezone@master
      with:
        timezone: Europe/Brussels
    - run: dotnet test SeatsioDotNet.Test --no-build --verbosity normal
